api_platform:
    title: API Tender Test
    description: 'API для взаимодействия с сервисом Tender Test'
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
    patch_formats:
        json: [ 'application/json' ]

    defaults:
        pagination_client_enabled: false
        collection:
            pagination:
                enabled_parameter_name: pagination # optional


    show_webby: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

