api_platform:
    title: API Tender Test
    description: 'API для взаимодействия с сервисом Tender Test'
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
    patch_formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']


    show_webby: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

