services:
  php-unit:
    build:
      context: .
      args:
        UID: ${DUID:-1000}
        GID: ${DGID:-1000}
      dockerfile: docker/${APP_ENV}/Dockerfile
    container_name: ${APP_NAME}-php
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_ALLOW_SUPERUSER: 1
    ports:
      - ${API_PORT}:80
    volumes:
      - .:/var/www/app:rw
      - ./unit-config.json:/docker-entrypoint.d/config.json:ro
    networks:
      - ${APP_NAME}-network
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_VERSION:-16.8}-alpine
    container_name: ${APP_NAME}-database
    ports:
      - 5432:5432
    volumes:
      - ${APP_NAME}_pgdata:/var/lib/postgresql/data:rw
      - ./docker/pgdata:/docker-entrypoint-database.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - ${APP_NAME}-network

volumes:
  tender_pgdata: ~


networks:
  tender-network:
    driver: bridge
