<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250420045628 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create tender table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE tender (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                title VARCHAR(255) NOT NULL, 
                number VARCHAR(255) NOT NULL, 
                external_code VARCHAR(255) DEFAULT NULL, 
                status VARCHAR(255) DEFAULT NULL, 
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
                PRIMARY KEY(id)
                )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_42057A7796901F54 ON tender (number)
        SQL);

    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP TABLE tender
        SQL);
    }
}
